/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;
/* Header for class com_xqs_cvdemo_OpenCVService */

#ifndef _Included_com_xqs_cvdemo_OpenCVService
#define _Included_com_xqs_cvdemo_OpenCVService
#ifdef __cplusplus
extern "C" {
#endif


int toGray(Mat img,Mat& gray);

JNIEXPORT jint JNICALL Java_com_xqs_cvdemo_OpenCVService_convertGray
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jbyteArray JNICALL Java_com_xqs_cvdemo_OpenCVService_rotateImg
        (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
